service: notification-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yaml):SendMailIAM}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yaml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yaml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yaml):Outputs.MailQueueUrl}

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  bundle:
    linting: false
