service: notification-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yaml):SendMailIAM}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    # events:
    #   - http:
    #       method: GET
    #       path: /hello

custom:
  bundle:
    linting: false
